# Generated by Django 4.2.9 on 2026-05-20 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField()),
                ('caller_user_id', models.UUIDField()),
                ('callee_user_id', models.UUIDField()),
                ('direction', models.CharField(choices=[('seeker_to_provider', 'Seeker to Provider'), ('provider_to_seeker', 'Provider to Seeker')], max_length=25)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed')], default='initiated', max_length=15)),
                ('exotel_call_sid', models.CharField(blank=True, max_length=100)),
                ('virtual_number', models.CharField(max_length=20)),
                ('duration_sec', models.IntegerField(default=0)),
                ('recording_url', models.CharField(blank=True, max_length=500)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
