[program:notification-consumer]
command=python manage.py consume_events
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=5
stopwaitsecs=10
stderr_logfile=/var/log/supervisor/notification-consumer.err.log
stdout_logfile=/var/log/supervisor/notification-consumer.out.log
environment=DJANGO_SETTINGS_MODULE="config.settings"
